### PR TITLE
Ticket 44 implement user profile edit page frontend

### PR DESCRIPTION
**Pull request by SimpFred**
The edit profile functionality is now implemented. Currently, only dummy data is being used, so when you refresh the page, the data reverts to its initial state since no database call is being made.

To test, you can log in as a user to see that the sections in Training Info are locked and when you go to a different id in the URL then your own the edit button should not show. Similarly, you can log in as a Teacher to verify that these sections are editable and that the edit button is visible for all id.

Currently, there’s no functionality implemented for changing the password, this need to be handled in its own issue.

### CODE REVIEW

**Comment by sebgro98** [comment]
When logged in as a teacher and trying to edit the dates im getting the following 
image

**Review by FredrikEH — COMMENTED** [review]
Should a user be able to have letters outside of the english alphabet, like å, ä and ö?

**Comment by SimpFred** [comment]
Will take a look at this @sebgro98

**Comment by SimpFred** [comment]
I do not now? Do we have some guide lines for that? @FredrikEH

**Comment by FredrikEH** [comment]
> I do not now? Do we have some guide lines for that? @FredrikEH

Good point, you can ignore that part of my comment.

**Comment by SimpFred** [comment]
It's fixed now. For the moment, you can enter anything in the fields. This might need to be reviewed when we start storing data in the database, especially regarding how we handle teachers and students.

**Review by FredrikEH — APPROVED** [review]

**Review by sebgro98 — APPROVED** [review]
Approved. But we need to look into validation in terms of what we can change the date to when logged in as a teacher

**Comment by amos1969** [comment]
Approved

**Pull request merged**
