### PR TITLE
Create cohort as a teacher

### PR DESCRIPTION
**Pull request by Valen98**
Now a teacher can add a cohort

Now a teacher can create a Cohort.

1. Sign in as a teacher into Cohort.
2. Press "Create Cohort", a modal will open
3. Write a name of the cohort
4. Click on the date picker icon and pick a date
6. do it again for endDate
image

8. Click "Create Cohort" and it should automatically refresh the cohort component and you should see the new Cohort.
9. 
image

### CODE REVIEW

**Review by FredrikEH — COMMENTED** [review]
I am getting a merge conflict when syncing with main. Did you update before your pull request?

**Comment by Valen98** [comment]
The main reason of merge conflict is in apiClient.js, in the bottom. I hope i fixed the merge conflict

**Review by FredrikEH — APPROVED** [review]

**Review by sebgro98 — APPROVED** [review]
Approved

**Comment by amos1969** [comment]
Approved

**Pull request merged**
